on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 * * * *' # Every hour
  push:
    tags:
    - '*'
  pull_request:
    types: [opened, edited]
name: Package manager test
jobs:
  homebrew:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            scripts/install-test.sh
          sparse-checkout-cone-mode: false
      - run: bash scripts/install-test.sh homebrew
  apt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            scripts/install-test.sh
          sparse-checkout-cone-mode: false
      - run: bash scripts/install-test.sh apt
  yum:
    runs-on: ubuntu-latest
    container: fedora:latest
    steps:
      - run: |
          if [ ! -d "/etc/yum.repos.d" ]; then
              sudo mkdir /etc/yum.repos.d
          fi
              echo "[Stripe]
          name=stripe
          baseurl=https://packages.stripe.dev/stripe-cli-rpm-local/
          enabled=1
          gpgcheck=0" | sudo tee /etc/yum.repos.d/stripe.repo

      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            scripts/install-test.sh
          sparse-checkout-cone-mode: false
      - run: bash scripts/install-test.sh yum
  scoop:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
      with:
        sparse-checkout: |
          scripts/install-test.sh
        sparse-checkout-cone-mode: false
    - uses: MinoruSekine/setup-scoop@v4
    - shell: powershell
      run: bash scripts/install-test.sh scoop
  docker:
    runs-on: ubuntu-latest
    container: stripe/stripe-cli:latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            scripts/install-test.sh
          sparse-checkout-cone-mode: false
      - run: sh scripts/install-test.sh docker
  pagerduty:
    needs: [docker, scoop, yum, apt, homebrew]
    runs-on: ubuntu-latest
    if: ${{ always() }}
    # if: ${{ always() && contains(needs.*.result, 'failure') }}
    steps:
      - shell: bash
        env:
          PAGERDUTY_INTEGRATION_KEY: ${{ secrets.PAGERDUTY_INTEGRATION_KEY }}
        run: |
          sh -c "$(curl -sL https://raw.githubusercontent.com/martindstone/pagerduty-cli/master/install.sh)"
          pd event alert --routing_key "$PAGERDUTY_INTEGRATION_KEY" \
            --summary "Failed to install Stripe CLI on one or more operating systems." \
            --timestamp date \
            --source "Stripe CLI GitHub Actions" \
            --severity critical \
            --keys run_details --values "https://github.com/stripe/stripe-cli/actions/workflows/install-test.yml"

